baseURL = "https://danicos.me"
languageCode = "en-us"
title = "Daniel Cosme"
theme = "hugo-developer-portfolio"



[module]
  [[module.imports]]
    path = "github.com/samrobbins85/hugo-developer-portfolio"

[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"

# navigation
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight=1

#  [[menu.main]]
#  name = "Blog"
#  URL = "blog"
#  weight=2

  [[menu.main]]
  name = "Projects"
  URL = "portfolio"
  weight=3

#  [[menu.main]]
#  name = "Contact"
#  URL = "contact"
#  weight=4

[params]
home = "Home"
# Meta data
description = "The website of Daniel Cosme, Software Engineer"
author = "Daniel Cosme"

  [params.contact]
  enable = false
  # Add your formspree URL here to get emails
  formAction = "" #contact form works with formspree.io

  [params.footer]
  email = "cosmedaniel8@gmail.com"
  address = "Montreal, CA"
  googlemaps = "#"

